### ISSUE TITLE
Package health and maintenance

### ISSUE THREAD

**Issue by apapsch** [Crowdstar/exponential-backoff#1]
Hi and thanks for publishing your package! I see your package is alive and well at the moment. Seeing other packages wither and die, I am wary of just adding a package without adapting its entire interface, to avoid having great pain when a package becomes abandoned.

Can you ensure maintenance for the foreseeable future? Do you ensure it professionally (as part of a software related job)? If you leave the company, will you abandon the package or continue maintenance (or maybe have someone to take over)? I'm not trying to commit you to anything, just trying to gauge your current commitment :-)

Best regards

**Comment by deminy** [comment]
Hi there. Glad there is someone interested in using the package, and thanks for bringing up the question.

This package was created and is maintained by me (with supports from my colleagues at [Glu Mobile](https://www.glu.com)). I have been playing with PHP for a long time,  and actively maintaining a few open source packages. I can see that I will keep doing that for the next couple of years, no matter where I am or which company I work for.

In a worst-case scenario, assuming that this package is not maintained anymore for whatever reason, it should still be fine. People can fork/copy this repository and use the forked one instead. Further maintenance and updates can be made to the new repository, and people can easily switch to the new repository by changing their `composer.json` file from

```json
{
    "require": {
        "crowdstar/exponential-backoff": "~3.0.0"
    }
}
```

to

```json
{
    "require": {
        "crowdstar/exponential-backoff": "~3.0.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://path/to/the/new/repository/exponential-backoff.git"
        }
    ]
}
```

**Comment by apapsch** [comment]
Thanks for the information.

Happy hacking!
